import {esc,money} from './common.js';
import {SKIN_TONES,EYE_COLORS,NATURAL_HAIR_COLORS,HAIR_COLORS,BODY_FRAMES,HAIR_STYLES,TORSO_STYLES,LEG_STYLES,SHOE_STYLES,JEWELRY_STYLES,CLOTHING_COLORS,BARBER_PRICES,WARDROBE_PRICES} from './lpc-catalog.js';
import {hydrateLpcPreviews} from './lpc-renderer.js';
const option=(value,label,current)=>`<option value="${esc(value)}"${value===current?' selected':''}>${esc(label)}</option>`;
const choices=(items,current)=>items.map(x=>typeof x==='string'?option(x,x,current):option(x.id,x.name,current)).join('');
const preview=a=>`<canvas width="180" height="150" class="lpc-preview" data-lpc-preview="${esc(JSON.stringify(a||{}))}" aria-label="LPC citizen appearance preview"></canvas>`;
const shop=(w,id)=>w.businesses.find(b=>b.id===id);
const near=(w,id)=>{const s=shop(w,id);return !!s&&!w.player.insideHouse&&Math.hypot(w.player.x-(s.x+2),w.player.y-(s.y+1))<=5;};
const routeButton=(w,id)=>{const s=shop(w,id);return s?`<button class="small secondary" data-style-route="${id}">${near(w,id)?`Open ${esc(s.name)}`:`Walk to ${esc(s.name)}`} ↗</button>`:'';};
function cosmeticFields(a){const c=a?.cosmetics||{};return `<div class="appearance-grid"><label class="field">Hair style<select name="hairStyle">${choices(HAIR_STYLES,c.hairStyle)}</select></label><label class="field">Hair color<select name="hairColor">${choices(HAIR_COLORS,c.hairColor)}</select></label><label class="field">Top<select name="torsoStyle">${choices(TORSO_STYLES,c.torsoStyle)}</select></label><label class="field">Top color<select name="torsoColor">${choices(CLOTHING_COLORS,c.torsoColor)}</select></label><label class="field">Legwear<select name="legStyle">${choices(LEG_STYLES,c.legStyle)}</select></label><label class="field">Legwear color<select name="legColor">${choices(CLOTHING_COLORS,c.legColor)}</select></label></div>`;}
function geneticsText(a){const g=a?.genetics||{};return `Skin ${esc(g.skinTone||'unknown')} · Natural hair ${esc(g.naturalHairColor||'unknown')} · Eyes ${esc(g.eyeColor||'unknown')} · Body frame ${esc(g.bodyFrame||'unknown')}`;}
const wardrobeLabel=item=>item==='none'?'No jewelry':item.split(':').map(s=>s.replaceAll('_',' ')).join(' · ');
function ownedWardrobe(citizen,category,bucket,current){const items=citizen.appearance?.wardrobe?.[bucket]||[];return `<div class="wardrobe-list">${items.map(item=>`<button class="small ${item===current?'':'secondary'}" data-equip-wardrobe="${esc(citizen.id)}" data-category="${category}" data-item="${esc(item)}" ${item===current?'disabled':''}>${item===current?'Wearing':'Wear'} ${esc(wardrobeLabel(item))}</button>`).join('')||'<p class="muted">Nothing owned in this category yet.</p>'}</div>`;}
function purchaseForm(citizen,category,styles,currentStyle,currentColor,price){return `<form data-buy-wardrobe="${esc(citizen.id)}" data-category="${category}"><div class="appearance-grid"><label class="field">Style<select name="style">${choices(styles,currentStyle)}</select></label><label class="field">Color<select name="color">${choices(CLOTHING_COLORS,currentColor)}</select></label></div><button class="small">Buy and wear · ${money(price)} ◈</button></form>`;}
function shopStatus(w,id){const s=shop(w,id);if(!s)return '<p class="economy-alert">Shop unavailable.</p>';return `<p class="muted">${esc(s.name)} · ${s.status} · ${s.inventory?.goods||0} supply units · ${s.employees?.length||0} staff</p>`;}
function activeCitizen(w){const id=w.player?.citizenId;return w.npcs?.find(n=>n.id===id&&n.ownerId===w.player.id)||w.npcs?.find(n=>n.id===id)||null;}
function activeStyleCard(w,c){const n=w.npcs.find(n=>n.id===c.id)||c,a=n.appearance||c.appearance,cos=a.cosmetics||{};const active=!!c.active;
 if(!active)return `<article class="business-card appearance-card">${preview(a)}<div><p class="eyebrow">Generation ${esc(n.generationLabel||'A')} · Owned citizen</p><h3>${esc(n.name)}</h3><p>${geneticsText(a)}</p><p class="muted">Take control of this citizen to change what they are wearing or take them to an appearance shop.</p></div></article>`;
 const topCurrent=`${cos.torsoStyle}:${cos.torsoColor}`,legCurrent=`${cos.legStyle}:${cos.legColor}`,shoeCurrent=`${cos.shoeStyle||'basic'}:${cos.shoeColor||'umber'}`,jewelryCurrent=cos.jewelryStyle==='none'?'none':`${cos.jewelryStyle}:${cos.jewelryColor||'gold'}`;
 return `<article class="business-card appearance-card">${preview(a)}<div><p class="eyebrow">Generation ${esc(n.generationLabel||'A')} · Active citizen</p><h3>${esc(n.name)}</h3><p>${geneticsText(a)}</p><p class="muted">This tab is your closet. You can freely wear items this citizen already owns. Hair services and new purchases only happen at the physical shop counter.</p>
 <h3>Hair</h3><p class="muted">Current: ${esc(cos.hairStyle)} · ${esc(cos.hairColor)}. Haircuts and dye require an in person visit.</p>${routeButton(w,'barber')}
 <h3>Owned tops</h3>${ownedWardrobe(n,'top','tops',topCurrent)}${routeButton(w,'tailor')}
 <h3>Owned legwear</h3>${ownedWardrobe(n,'legs','legs',legCurrent)}${routeButton(w,'tailor')}
 <h3>Owned shoes</h3>${ownedWardrobe(n,'shoes','shoes',shoeCurrent)}${routeButton(w,'cobbler')}
 <h3>Owned jewelry</h3>${ownedWardrobe(n,'jewelry','jewelry',jewelryCurrent)}${routeButton(w,'jeweler')}
 </div></article>`;}
function newbornCard(w,c){const a=c.appearance||{},o=a.geneticOptions||{},g=a.genetics||{},day=w.day-1,remaining=Math.max(0,(c.appearanceCustomizeUntilDay??day)-day);return `<article class="business-card appearance-card">${preview(a)}<div><p class="eyebrow">Newborn appearance window · ${remaining} town day${remaining===1?'':'s'} left</p><h3>${esc(c.name)} · Generation ${esc(c.generationLabel||'B')}</h3><p class="muted">Birth customization establishes this child's inherited identity and starter outfit. After this window, later changes use the normal shop economy.</p><form data-newborn-style="${esc(c.id)}"><div class="appearance-grid"><label class="field">Skin tone<select name="skinTone">${choices(o.skinTone||SKIN_TONES,g.skinTone)}</select></label><label class="field">Natural hair<select name="naturalHairColor">${choices(o.naturalHairColor||NATURAL_HAIR_COLORS,g.naturalHairColor)}</select></label><label class="field">Eye color<select name="eyeColor">${choices(o.eyeColor||EYE_COLORS,g.eyeColor)}</select></label><label class="field">Body frame<select name="bodyFrame">${choices(o.bodyFrame||BODY_FRAMES,g.bodyFrame)}</select></label></div>${cosmeticFields(a)}<button class="small">Save inherited appearance</button></form></div></article>`;}
export function appearanceShopCounter(w,b){
 if(!b?.serviceKind)return '';
 const citizen=activeCitizen(w),here=near(w,b.id);
 if(!citizen)return `<section class="appearance-counter"><h3>Appearance counter</h3><p class="muted">Take control of one of your citizens before using this shop.</p></section>`;
 if(!here)return `<section class="appearance-counter"><h3>Appearance counter</h3><p class="muted">Purchases and cosmetic services are only available while ${esc(citizen.name)} is physically standing at this shop.</p>${routeButton(w,b.id)}</section>`;
 if(b.status!=='open')return `<section class="appearance-counter"><h3>Appearance counter</h3><p class="economy-alert">${esc(b.name)} is currently closed.</p></section>`;
 const a=citizen.appearance||{},cos=a.cosmetics||{};
 if(b.serviceKind==='barber')return `<section class="appearance-counter"><h3>Barber counter</h3>${shopStatus(w,'barber')}<p class="muted">Services change the active citizen immediately and must be purchased here each time.</p><form data-barber-service="${esc(citizen.id)}"><div class="appearance-grid"><label class="field">Hair style · ${BARBER_PRICES.hairStyle} ◈ if changed<select name="hairStyle">${choices(HAIR_STYLES,cos.hairStyle)}</select></label><label class="field">Hair color · ${BARBER_PRICES.hairColor} ◈ if changed<select name="hairColor">${choices(HAIR_COLORS,cos.hairColor)}</select></label></div><button class="small">Pay barber and apply</button></form></section>`;
 if(b.serviceKind==='tailor')return `<section class="appearance-counter"><h3>Tailor counter</h3>${shopStatus(w,'tailor')}<p class="muted">Buy new clothing here. Purchased pieces are added to ${esc(citizen.name)}'s wardrobe and can later be equipped for free from Style.</p><h4>Tops</h4>${purchaseForm(citizen,'top',TORSO_STYLES,cos.torsoStyle,cos.torsoColor,WARDROBE_PRICES.top)}<h4>Legwear</h4>${purchaseForm(citizen,'legs',LEG_STYLES,cos.legStyle,cos.legColor,WARDROBE_PRICES.legs)}</section>`;
 if(b.serviceKind==='cobbler')return `<section class="appearance-counter"><h3>Cobbler counter</h3>${shopStatus(w,'cobbler')}<p class="muted">Buy footwear here. Owned shoes remain in this citizen's wardrobe.</p>${purchaseForm(citizen,'shoes',SHOE_STYLES,cos.shoeStyle||'basic',cos.shoeColor||'umber',WARDROBE_PRICES.shoes)}</section>`;
 if(b.serviceKind==='jeweler')return `<section class="appearance-counter"><h3>Jeweler counter</h3>${shopStatus(w,'jeweler')}<p class="muted">Buy jewelry here. Removing or re equipping owned jewelry is free from Style.</p>${purchaseForm(citizen,'jewelry',JEWELRY_STYLES.filter(x=>x.id!=='none'),cos.jewelryStyle==='none'?'stud':cos.jewelryStyle,cos.jewelryColor||'gold',WARDROBE_PRICES.jewelry)}</section>`;
 return '';
}
export function appearancePanel(w){const owned=w.citizenship?.characters||[],day=w.day-1,newborns=(w.children||[]).filter(c=>!c.grown&&(c.appearanceCustomizationOwners||[]).includes(w.player.id)&&day<=Number(c.appearanceCustomizeUntilDay??-1));return `<span class="eyebrow">Everwick wardrobe</span><h2>Wear what you own.</h2><p>The Style tab is now a closet, not a store. Equip owned clothing, shoes, and jewelry here for free. To buy something new or change hair, physically visit the correct shop and open its counter.</p><div class="profile-stats"><span>Owned citizens</span><strong>${owned.length}</strong><span>Newborn designs waiting</span><strong>${newborns.length}</strong><span>Appearance shops</span><strong>4</strong></div>${newborns.length?`<h3>Newborn customization</h3>${newborns.map(c=>newbornCard(w,c)).join('')}`:''}<h3>Your citizens</h3>${owned.map(c=>activeStyleCard(w,c)).join('')||'<p class="muted">Claim a founder to begin styling citizens.</p>'}<p class="muted">New cosmetic purchases transfer existing Everwick coins to the shop and consume shop supplies. Character artwork uses the Liberated Pixel Cup ecosystem. See the <a href="/credits" target="_blank" rel="noopener">Everwick credits page</a> for artist and license information.</p>`;}
export {hydrateLpcPreviews};
