import {esc} from './common.js';
export const CHAPTER=[
 {title:'A town that needs you',text:'The clinic is short of supplies. Meet the town clerk outside Town Hall to take a delivery contract.',x:34,y:14,button:'Speak to the clerk'},
 {title:'Collect the supplies',text:'Walk to Sunfield Farm. The town pays the farmer for five food supplies; you carry them to the clinic.',x:9,y:28,button:'Collect five supplies'},
 {title:'Keep your promise',text:'Bring the sealed supplies to Willow Clinic. This delivery puts real stock into the clinic and earns 1,000 coins.',x:29,y:29,button:'Deliver to the clinic'},
 {title:'Put down roots',text:'Buy a starter home from the Homes panel (~900 ◈). Existing home owners can claim this milestone too. Earn 500 coins toward furnishing it.',button:'Claim home milestone'},
 {title:'Make it yours',text:'Enter your home, buy furniture and place at least one item. Return here to collect 400 coins.',button:'Claim decoration milestone'},
 {title:'A stake in the high street',text:'Buy the Green Dragon Tavern starter listing (1,200 ◈) — or any business you already own qualifies. Finish the chapter for 600 coins.',button:'Complete the chapter'}];
export function chapterPanel(w){const q=w.player.chapter||{step:0},s=CHAPTER[q.step];return `<span class="eyebrow">Your first chapter</span><h2>${s?s.title:'You belong here.'}</h2><progress aria-label="First chapter progress" max="6" value="${q.step}"></progress><p>${q.step}/6 milestones complete</p>${s?`<p>${s.text}</p>${q.step===3?'<button data-chapter-panel="properties">Browse starter homes →</button>':q.step===4?'<button data-chapter-panel="properties">Open my home →</button>':q.step===5?'<button data-chapter-panel="business">Browse businesses →</button>':''}${s.x?`<p class="memory">Walk to the marked destination, then use “${s.button}” below.</p><button id="chapterRoute" class="secondary">Walk to ${q.step===0?'Town Hall':q.step===1?'Sunfield Farm':'Willow Clinic'} →</button>`:''}<button id="chapterAction">${s.button}</button>`:'<p>You helped the clinic, made a home and joined the high street. Your businesses, neighbours and town projects continue beyond this chapter.</p>'}<details class="story-extras"><summary>Need more coins? Delivery contracts</summary><p>Collect a sealed food shipment at the farm and deliver it to the clinic for 120 coins. Stock and funds must be available. One completed delivery per six town hours.</p><button id="contractRoute">Route to ${w.player.contract?'clinic':'farm'}</button><button id="contractAction">${w.player.contract?'Deliver shipment':'Collect shipment'}</button>${w.player.contract?'<p>Carrying five sealed supplies. They cannot be sold or duplicated.</p>':''}</details><h3>Your story so far</h3>${(q.log||[]).map(t=>`<p class="memory">${esc(t)}</p>`).join('')||'<p>Your first page is waiting.</p>'}`;}
