import {esc,money} from './common.js';
export function communityPanel(w){const people=(w.players||[]).filter(p=>p.id!==w.player.id);return `<span class="eyebrow">A town of neighbours</span><h2>Meet someone.</h2><p>Move within five tiles to wave, talk or share supplies. House visitors can interact with people in the same room.</p>${people.map(p=>`<article class="business-card"><strong>${esc(p.name)}</strong><p>${p.insideHouse?'Visiting a home':`At ${Math.round(p.x)}, ${Math.round(p.y)}`}</p>${buttons(p.id)}<form data-social-chat="${p.id}"><label class="field">Say something<input name="message" maxlength="200" required></label><button>Send nearby message</button></form></article>`).join('')||'<p>No other players online. Sign in with a separate account to meet here.</p>'}<h3>Recent interactions</h3>${(w.socialFeed||[]).slice().reverse().map(e=>`<p class="memory"><strong>${esc(e.fromName)} → ${esc(e.toName)}</strong><br>${esc(e.text)}</p>`).join('')||'<p>Wave to a neighbour to begin.</p>'}`;}
export function buttons(id){return `<div class="actions"><button data-social="wave" data-target="${id}">Wave</button><button data-social="gift-coins" data-target="${id}">Give 25 coins</button><button data-social="gift-food" data-target="${id}">Share one food</button></div>`;}
function citizenName(w,id){return w.npcs.find(n=>n.id===id)?.name||(w.children||[]).find(c=>c.id===id)?.name||id;}
function townName(w,id){return w.civilization?.settlements?.find(t=>t.id===id)?.name||(id==='everwick'?'Everwick':id);}
function ownedCard(w,c){const listing=w.citizenship?.marketplace?.find(l=>l.citizenId===c.id&&l.status==='active'),canResell=(c.generation||0)>0||c.founderResaleEligible;return `<article class="business-card"><p class="eyebrow">Generation ${esc(c.generationLabel||'A')} · Age ${c.age}</p><h3>${esc(c.name)}</h3><p>${esc(c.occupation||'Citizen')} · ${esc(townName(w,c.settlementId))}</p>${c.active?'<span class="badge">Currently controlled</span>':`<button class="small" data-citizen-switch="${c.id}">Take control</button>`}${c.starter?'<p class="muted">Free starter · Generation S · Cannot breed or transfer. Work, Story, homes, businesses and dungeons are available.</p>':listing?`<p class="muted">Listed for ${money(listing.price)} ◈</p><button class="small secondary" data-citizen-cancel="${listing.id}">Cancel listing</button>`:!canResell&&((c.generation||0)===0)?'<p class="muted">Founder A · Primary ownership must first be purchased through Stripe. Development preview founders are not coin resale eligible.</p>':!c.active?`<form data-citizen-list="${c.id}"><label class="field">Marketplace price<input name="price" type="number" min="100" max="100000" value="1500" required></label><button class="small secondary">List citizen</button></form>`:''}</article>`;}
function marketCard(w,l){const c=l.citizen;return `<article class="business-card"><p class="eyebrow">Generation ${esc(c.generationLabel||'A')} · Age ${c.age}</p><h3>${esc(c.name)}</h3><p>${esc(c.occupation)} · ${esc(townName(w,c.settlementId))}</p><p>Health ${Math.round(c.health||0)}/100 · ${Object.entries(c.skills||{}).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')}</p><strong>${money(l.price)} ◈</strong>${l.mine?`<button class="small secondary" data-citizen-cancel="${l.id}">Cancel your listing</button>`:`<button class="small" data-citizen-buy="${l.id}">Buy control rights</button>`}</article>`;}
export function populationPanel(w){
 const active=w.npcs.filter(n=>n.residency!=='away'),children=(w.children||[]).filter(c=>!c.grown),towns=w.civilization?.settlements||[],aging=w.population?.aging||{daysPerYear:3,adultAge:18},owned=w.citizenship?.characters||[],market=w.citizenship?.marketplace||[],households=w.population?.households||[];
 return `<span class="eyebrow">Lineages, households and citizen ownership</span><h2>Generations.</h2><p>Every founding citizen is Generation A. A child is always one generation beyond the older lineage of their parents. A + A creates B. A + B creates C. B + B creates C. A–Y can breed when household requirements are met; Z is sterile. Each parent can have at most 50 births, and cooldowns increase with generation. Your free Generation S starter cannot breed or be transferred.</p><div class="profile-stats"><span>Adults on Everwick map</span><strong>${active.length}</strong><span>Citizens elsewhere</span><strong>${w.npcs.length-active.length}</strong><span>Dependent children</span><strong>${children.length}</strong><span>Aging rate</span><strong>1 year / ${aging.daysPerYear} town days</strong></div><p>Children become full citizens at age ${aging.adultAge}. Until then they remain dependents. Birth only occurs in partnered households that meet minimum health, happiness, relationship, housing, food, and financial stability requirements.</p>
 <h3>Your citizens</h3><p>You can own multiple adult citizens, but directly control only one at a time. Citizens you are not controlling continue their autonomous lives.</p>${owned.map(c=>ownedCard(w,c)).join('')||'<p class="muted">Your first citizenship will appear here.</p>'}
 <h3>Citizen marketplace</h3><p>Generation A citizens are founders. Their first player ownership must come through the Stripe founder citizenship flow. After a specific A founder has completed that primary paid acquisition, its owner may resell its control rights on this marketplace for in game coins. Unowned A founders and development preview A founders cannot be bought for coins. Generation B and every later generation use the in game marketplace normally. Buying a citizen does not reset their life. Their family, age, possessions, memories, job, residence, and history stay intact.</p>${market.slice(0,24).map(l=>marketCard(w,l)).join('')||'<p class="muted">No adult citizens are listed right now.</p>'}
 ${towns.length?`<h3>Where people live</h3>${towns.map(t=>`<p><strong>${esc(t.name)}</strong> · ${t.stats.population} adults · ${t.stats.openings} open jobs · ${t.stats.averageWage} ◈ average wage</p>`).join('')}`:''}
 <h3>Household readiness</h3>${households.map(h=>`<article class="business-card"><strong>${h.partners.map(id=>esc(citizenName(w,id))).join(' & ')}</strong><p>Readiness ${h.score}/100 · Health ${h.health} · Happiness ${h.happiness} · Relationship ${h.relationship}</p><p>Dependent children ${h.children} · Open household spaces ${h.space}</p><span class="badge">${h.ready?'Healthy home, family growth possible':'Not currently ready for children'}</span></article>`).join('')||'<p class="muted">Stable partnerships will appear here as relationships form.</p>'}
 <h3>The next generation</h3>${children.map(c=>`<article class="business-card"><strong>${esc(c.name)}</strong><p>Age ${c.age} · Generation ${esc(c.generationLabel||'B')} · Born in ${esc(c.birthplace||'Everwick')}</p><p>Parents: ${(c.parents||[]).map(id=>esc(citizenName(w,id))).join(' & ')}</p><p>${Object.entries(c.genes||{}).map(([k,v])=>`${esc(k)} ${v.join('/')}`).join(' · ')}</p></article>`).join('')||'<p>No dependent children yet.</p>'}
 <h3>Arrivals, births and coming of age</h3>${(w.population?.history||[]).map(h=>`<p class="memory">Day ${h.day}: <strong>${esc(h.title)}</strong><br>${esc(h.body)}</p>`).join('')||'<p>The founding generation is settling in.</p>'}`;
}
