export const $=s=>document.querySelector(s);
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money=n=>new Intl.NumberFormat('en-US').format(n||0);
export async function api(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()}:{},body:data?JSON.stringify(data):undefined});const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
let toastTimer;export function toast(message){let node=$('#toast');if(!node){node=document.createElement('div');node.id='toast';node.className='toast';node.setAttribute('role','status');document.body.append(node);}node.textContent=message;node.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.hidden=true,6500);}
export function authModal(after=()=>location.reload()){
 const dialog=document.createElement('dialog');let registering=true;
 function render(){dialog.innerHTML=`<button class="close" aria-label="Close">×</button><span class="eyebrow">A new chapter starts here</span><h2>${registering?'Create your free account':'Welcome back'}</h2><form id="authForm">${registering?'<label class="field">Account name<input name="name" autocomplete="nickname" minlength="2" maxlength="32" required></label>':''}<label class="field">Email<input name="email" type="email" autocomplete="email" required></label><label class="field">Password<input name="password" type="password" autocomplete="${registering?'new-password':'current-password'}" minlength="12" maxlength="128" required></label><p class="muted" style="font-size:13px">Use at least 12 characters. One free starter citizen is included. Your account name is separate from your citizen’s name.</p><p class="form-error" role="alert"></p><button type="submit">${registering?'Enter Everwick':'Sign in'} →</button></form><button class="text-button" id="switchAuth">${registering?'Already a citizen? Sign in':'New here? Create an account'}</button>`;
 dialog.querySelector('.close').onclick=()=>dialog.close();dialog.querySelector('#switchAuth').onclick=()=>{registering=!registering;render();};dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=dialog.querySelector('[type=submit]');btn.disabled=true;try{await api(`/api/auth/${registering?'register':'login'}`,Object.fromEntries(new FormData(e.target)));dialog.close();after();}catch(err){dialog.querySelector('.form-error').textContent=err.message;}finally{btn.disabled=false;}};}
 render();document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();
}
export function track(event,extra={}){api('/api/analytics',{event,source:new URLSearchParams(location.search).get('utm_source')||'direct',...extra}).catch(()=>{});}

