import {esc,money} from './common.js';
import {DUNGEON_ENTRANCE} from './world-map.js';

const distance=w=>Math.hypot((w.player?.x||0)-DUNGEON_ENTRANCE.x,(w.player?.y||0)-DUNGEON_ENTRANCE.y);
const resultText=r=>{if(!r)return '<p class="muted">No expedition has been recorded yet.</p>';if(r.status==='success')return `<p class="memory"><strong>Last run cleared.</strong> ${r.steps} steps. Reward: ${r.reward?.coins||0} coins, ${r.reward?.ore||0} ore, ${r.reward?.goods||0} goods${r.reward?.artifact?`, ${r.reward.artifact} artifact`:''}.</p>`;if(r.status==='death')return `<p class="memory"><strong>Last run ended in defeat.</strong> Lost ${r.lostCoins||0} coins${r.lostItem?` and one ${esc(r.lostItem)}`:''}${r.relicLost?' plus the claimed relic':''}.</p>`;return `<p class="memory"><strong>Last run abandoned.</strong> No reward was earned${r.relicLost?', and the claimed relic was left behind':''}.</p>`;};

export function dungeonPanel(w){const run=w.player?.dungeonRun,stats=w.player?.dungeonStats||{runs:0,completions:0,deaths:0,abandons:0};if(!run?.active){const here=!w.player.insideHouse&&distance(w)<=4.5;return `<span class="eyebrow">Player only expedition</span><h2>Copperhill Catacombs.</h2><p>Every descent generates a new maze. Autonomous citizens cannot enter or complete it. Find three rune seals, survive the hazards, then reach the sealed exit.</p><div class="profile-stats"><div><span>Runs</span><strong>${stats.runs||0}</strong></div><div><span>Clears</span><strong>${stats.completions||0}</strong></div><div><span>Deaths</span><strong>${stats.deaths||0}</strong></div><div><span>Best clear</span><strong>${stats.bestSteps==null?'None':stats.bestSteps+' steps'}</strong></div></div><section class="dungeon-rules"><h3>Risk and reward</h3><p>If your citizen falls, recovery takes 12 percent of carried coins up to 500, one carried inventory item when available, health, and energy. A clear pays a treasury bounty and returns real ore and goods to your inventory.</p></section>${resultText(w.player.lastDungeonResult)}<p class="muted">Entrance: Copperhill Ridge, near the mine. ${here?'You are standing at the entrance.':`You are ${Math.round(distance(w))} tiles away.`}</p><div class="actions"><button data-dungeon-route class="secondary">${here?'Show entrance':'Walk to entrance'}</button><button data-dungeon-enter ${here?'':'disabled'}>Enter generated dungeon</button></div>`;}
 const seals=run.seals.filter(s=>s.taken).length,enc=run.encounter,health=Math.max(0,Math.round(run.health)),shrines=(run.shrines||[]).filter(s=>s.used).length,relic=run.relic?.claimed?'Secured':'Unclaimed';return `<span class="eyebrow">Dungeon run ${esc(run.id)}</span><h2>The catacombs shift around you.</h2><div class="profile-stats"><div><span>Health</span><strong>${health}/${run.maxHealth}</strong></div><div><span>Rune seals</span><strong>${seals}/3</strong></div><div><span>Relic vault</span><strong>${relic}</strong></div><div><span>Shrines used</span><strong>${shrines}/${(run.shrines||[]).length}</strong></div></div><progress class="need-progress" value="${health}" max="${run.maxHealth}">${health}</progress><section class="dungeon-objectives"><h3>Expedition choices</h3><p><strong>Blue rune seals</strong> unlock the exit. <strong>Gold vaults</strong> add an artifact only if you clear the run. <strong>Green shrines</strong> mend wounds; <strong>violet shrines</strong> reveal a nearby objective.</p><div class="profile-stats"><div><span>Steps</span><strong>${run.steps}</strong></div><div><span>Guardians defeated</span><strong>${run.kills}</strong></div></div></section>${enc?`<section class="dungeon-encounter"><span class="eyebrow">Guardian encounter</span><h3>${esc(enc.name)}</h3><p>Guardian health: ${enc.hp}/${enc.maxHp}. Movement is blocked until you defeat it or escape.</p><div class="dungeon-actions"><button data-dungeon-fight="strike">Strike</button><button data-dungeon-fight="guard" class="secondary">Guard</button><button data-dungeon-fight="ration" class="secondary">Use food ration</button><button data-dungeon-fight="flee" class="secondary">Flee</button></div></section>`:`<p class="muted">Use WASD or the arrow keys on the main map to explore. The exit remains locked until all three rune seals are found.</p>`}<h3>Expedition log</h3>${(run.log||[]).map(x=>`<p class="memory">${esc(x)}</p>`).join('')||'<p class="muted">The halls are quiet.</p>'}<button data-dungeon-abandon class="secondary">Abandon run and return outside</button>`;}

export {DUNGEON_ENTRANCE};
