import {esc} from './common.js';
const coins=n=>Number(n||0).toLocaleString();
const pct=n=>`${Number(n||0)}%`;
function serviceRows(t){return Object.entries(t.services).map(([k,v])=>`<div class="profile-stats"><span>${esc(k)}</span><strong>${v}/100</strong></div>`).join('');}
function developmentRows(t){const d=t.development||{};return `<div class="profile-stats"><span>Town Hall</span><strong>${d.townHall||0}</strong><span>Housing rows</span><strong>${d.housing||0}</strong><span>Stores</span><strong>${d.stores||0}</strong><span>Workshops</span><strong>${d.workshops||0}</strong></div>`;}
function frontierCard(f){
 const hall=f.hall||{status:'unbuilt',work:0,required:4};
 let action=`<button class="small secondary" data-travel="${f.id}">Travel to ${esc(f.name)} · 25 ◈</button>`;
 if(!f.settlementId&&f.nearby&&hall.status==='unbuilt')action+=` <button class="small" data-start-hall="${f.id}">Break ground on Town Hall · 600 ◈</button>`;
 if(!f.settlementId&&hall.status==='building')action+=f.nearby?` <button class="small" data-work-hall="${f.id}">Build Town Hall · shift ${Math.min(hall.required,hall.work+1)}/${hall.required}</button>`:` <span class="muted">Travel here to continue construction.</span>`;
 if(!f.settlementId&&hall.status==='complete')action+=f.nearby?`<form data-charter-site="${f.id}"><label class="field">Town name<input name="name" minlength="3" maxlength="28" placeholder="New Haven" required></label><label class="field">Economic focus<select name="focus"><option value="balanced" ${f.focus==='balanced'?'selected':''}>Balanced</option><option value="agriculture" ${f.focus==='agriculture'?'selected':''}>Agriculture</option><option value="industry" ${f.focus==='industry'?'selected':''}>Industry</option><option value="trade" ${f.focus==='trade'?'selected':''}>Trade</option></select></label><button>Charter township · 2,200 ◈</button></form>`:` <p class="muted">The Town Hall is ready. Return here to sign the charter.</p>`;
 if(f.settlementId)action+=` <span class="badge">Chartered as ${esc(f.town||'township')}</span>`;
 return `<article class="business-card"><p class="eyebrow">${esc(f.biome)} frontier · ${esc(f.stage)}</p><h2>${esc(f.name)}</h2><h3>${esc(f.landmark.name)}</h3><p>${esc(f.landmark.description)}</p><div class="profile-stats"><span>Production specialty</span><strong>${esc(f.landmark.label)}</strong><span>Landmark output</span><strong>×${Number(f.landmark.bonus).toFixed(2)}</strong><span>Town Hall</span><strong>${esc(hall.status)}${hall.status==='building'?` ${hall.work}/${hall.required}`:''}</strong></div>${action}</article>`;
}
function policyForm(t){return `<h3>Mayor controls</h3><p class="muted">Local policy changes wages, living costs, services and migration decisions.</p>
<form data-town-tax="${t.id}"><label class="field">Income tax percent<input type="number" name="incomeTax" min="0" max="25" value="${t.taxes.incomeTax}" required></label><button class="small">Set income tax</button></form>
<form data-town-wage="${t.id}"><label class="field">Minimum daily wage<input type="number" name="minimumWage" min="10" max="150" value="${t.policies.minimumWage}" required></label><button class="small">Set minimum wage</button></form>
<form data-town-incentive="${t.id}"><label class="field">Migration incentive<input type="number" name="migrationIncentive" min="0" max="250" value="${t.policies.migrationIncentive}" required></label><button class="small">Set incentive</button></form>
<form data-town-immigration="${t.id}"><label class="field">Migration policy<select name="immigration"><option value="open" ${t.policies.immigration==='open'?'selected':''}>Open</option><option value="managed" ${t.policies.immigration==='managed'?'selected':''}>Managed</option><option value="restricted" ${t.policies.immigration==='restricted'?'selected':''}>Restricted</option></select></label><button class="small">Save migration policy</button></form>
<form data-town-zoning="${t.id}"><label class="field">Zoning priority<select name="zoning">${['balanced','residential','commercial','industrial','agricultural'].map(v=>`<option value="${v}" ${t.policies.zoning===v?'selected':''}>${v[0].toUpperCase()+v.slice(1)}</option>`).join('')}</select></label><button class="small">Save zoning</button></form>
${t.siteId?`<h3>Build the town</h3><p class="muted">Physical development must be commissioned while you are at the township site. Housing creates room for migrants. Stores and workshops create jobs.</p><button class="small secondary" data-travel="${t.siteId}">Travel to town · 25 ◈</button> ${t.nearby?`<button class="small" data-town-build="housing" data-town="${t.id}">Build housing row · 700 ◈</button> <button class="small" data-town-build="store" data-town="${t.id}">Build general store · 900 ◈</button> <button class="small" data-town-build="workshop" data-town="${t.id}">Build workshop · 1,200 ◈</button>`:`<span class="muted">Travel there to construct buildings.</span>`}`:''}
<h3>Public investment</h3>${Object.keys(t.services).map(k=>`<button class="small secondary" data-fund-service="${k}" data-town="${t.id}">Fund ${esc(k)} · 250 ◈</button>`).join(' ')}
<h3>Economic development</h3>${t.sectors.map(s=>`<button class="small secondary" data-expand-sector="${s.id}" data-town="${t.id}">Expand ${esc(s.name)} · 1,200 ◈</button>`).join(' ')}`;}
function settlementCard(t){const stock=Object.entries(t.stock||{}).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')||'No regional stock yet',today=Object.entries(t.productionToday||{}).map(([k,v])=>`${esc(k)} +${v}`).join(' · ')||'No landmark production today';return `<article class="business-card"><p class="eyebrow">${esc(t.identity)} · Founded day ${t.foundedDay}</p><h2>${esc(t.name)}</h2><p><strong>Mayor ${esc(t.mayorName)}</strong></p>${t.landmark?`<p><strong>${esc(t.landmark.name)}</strong> · ${esc(t.landmark.label)} production ×${Number(t.landmark.bonus).toFixed(2)}</p>`:''}<div class="profile-stats"><span>Population</span><strong>${t.stats.population}</strong><span>Open jobs</span><strong>${t.stats.openings}</strong><span>Average wage</span><strong>${t.stats.averageWage} ◈</strong><span>Unemployment</span><strong>${pct(t.stats.unemployment)}</strong><span>Housing</span><strong>${t.stats.population}/${t.housingCapacity}</strong><span>Average rent</span><strong>${t.rentIndex} ◈</strong><span>Land value</span><strong>${t.landValue}</strong><span>Treasury</span><strong>${coins(t.treasuryCash)} ◈</strong><span>Quality of life</span><strong>${t.stats.qualityOfLife}/100</strong></div>${developmentRows(t)}<p class="muted">Taxes: income ${pct(t.taxes.incomeTax)} · business ${pct(t.taxes.businessTax)} · sales ${pct(t.taxes.salesTax)} · property ${pct(t.taxes.propertyTax)}</p><p class="muted">Regional stock: ${stock}</p><p class="muted">Today: ${today}</p><h3>Job market</h3>${t.sectors.length?t.sectors.map(s=>`<p><strong>${esc(s.name)}</strong> · ${s.wage} ◈ daily · ${s.employed}/${s.slots} filled · ${s.openings} openings</p>`).join(''):'<p>Everwick uses its individual business payrolls as its labor market.</p>'}<h3>Public services</h3>${serviceRows(t)}<h3>Town capital</h3><button class="small secondary" data-town-contribute="${t.id}" data-amount="500">Contribute 500 ◈</button>${t.canGovern?policyForm(t):`<button class="small secondary" data-candidacy="${t.id}">Declare mayoral candidacy</button>`}</article>`;}
export function governmentPanel(w){const c=w.civilization;if(!c)return '<p>Regional government is initializing.</p>';return `<span class="eyebrow">From one citizen to a civilization</span><h2>Frontiers, townships and government.</h2><p>New towns now begin as physical places in the world. Travel to an undeveloped region, build its Town Hall, sign a charter, then build housing and employers. Unclaimed citizens compare those opportunities against their current life and can migrate.</p><article class="business-card"><h3>Government hierarchy</h3><p><strong>${esc(c.nation.name)}</strong><br>Chancellor ${esc(c.nation.government.chancellor.name)}</p><p>↓</p><p><strong>${esc(c.region.name)}</strong><br>Governor ${esc(c.region.government.governor.name)}</p><p>↓</p><p><strong>${c.settlements.length} local governments</strong><br>Mayors, councils, treasuries and local policy</p></article><h3>Buildable frontier regions</h3>${c.frontiers.map(frontierCard).join('')}<h3>Chartered settlements</h3>${c.settlements.map(settlementCard).join('')}<h3>Migration ledger</h3>${c.migrationLog.map(m=>`<p class="memory">Day ${m.day}: ${esc(m.text)}</p>`).join('')||'<p class="muted">No intertown migration has occurred yet.</p>'}`;}
