import {$,api,esc,money,toast,authModal,track} from './common.js';
import {TownRenderer} from './town.js';
track('page_view');const renderer=new TownRenderer($('#heroTown'),{preview:true});
async function refresh(){try{const data=await api('/api/public');const f=data.funding;const salesOpen=f.configured&&f.sales_enabled===true;$('#fundingGoal').textContent=f.mode==='test'?'test payments · no real funding':`of $${money(f.goal/100)}`;$('#raised').textContent=`$${money(f.raised/100)}`;$('#founderCount').textContent=`${f.founders} founders · Verified ${f.mode==='test'?'test-mode':'live'} payments, less refunds`;$('#fundingMode').textContent=f.mode==='test'?'TEST MODE · NOT REAL FUNDING':'FOUNDER FUNDING';$('#fundingBar').style.width=`${Math.min(100,f.raised/f.goal*100)}%`;$('#tiers').innerHTML=Object.entries(data.tiers).filter(([id])=>id!=='citizen').map(([id,t])=>`<article class="tier"><span class="eyebrow">${id==='town'?'A little more belonging':'Founding collection'}</span><h3>${esc(t.name)}</h3><div class="price">$${t.amount/100}</div><ul>${t.benefits.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${salesOpen?`<button data-tier="${id}">Choose package →</button>`:`<p class="sales-status">${f.sales_enabled===false?'Sales paused · alpha play is free':'Checkout unavailable · alpha play is free'}</p>`}</article>`).join('');$('#paymentNote').textContent=!salesOpen?'Sales paused or unavailable · alpha play is free. No checkout is available.':f.configured?'Checkout is in '+f.mode+' mode. Founder benefits are planned for future releases.':'Checkout is not configured. No payments can be taken in this installation. Future benefits are not yet delivered.';
 document.querySelectorAll('[data-tier]').forEach(btn=>btn.onclick=async()=>{track('founder_click');if(!salesOpen){toast('Stripe is not configured yet. Join the waitlist for founder campaign updates.');$('#community').scrollIntoView();return;}try{const me=await api('/api/me');if(!me.user)return authModal(()=>btn.click());const result=await api('/api/checkout',{tier:btn.dataset.tier});location.assign(result.url);}catch(e){toast(e.message);}});
 if(data.news[0]){const n=data.news[0];$('#headline').textContent=n.headline;$('#headlineBody').textContent=n.stories.at(-1)?.body||'A quiet day in Everwick.';$('#paperDate').textContent=`DAY ${n.day} · THE EVERWICK EDITION`;$('#liveStory').textContent=n.headline;}
 if(data.contact){$('#contact').textContent=`Contact: ${data.contact}`;}
 const preview=await api('/api/town-preview');renderer.setWorld(preview);$('#residentTotal').textContent=money(preview.npcs.length);$('#businessTotal').textContent=money(preview.businesses.length);$('#liveDay').textContent=`DAY ${Math.floor(preview.tick/24)+1} · ${String(preview.tick%24).padStart(2,'0')}:00`;
 }catch(e){toast(e.message);}}
refresh();setInterval(refresh,30000);
$('#waitlistForm').onsubmit=async e=>{e.preventDefault();const form=e.target,btn=form.querySelector('button');btn.disabled=true;try{const params=new URLSearchParams(location.search),r=await api('/api/waitlist',{email:form.email.value,consent:form.consent.checked,ref:params.get('ref'),source:params.get('utm_source')||'direct'});$('#waitResult').textContent=r.message;if(r.url){const a=document.createElement('a');a.href=r.url;a.textContent=r.url;$('#waitResult').append(document.createElement('br'),a);}}catch(err){toast(err.message);}finally{btn.disabled=false;}};
api('/api/referrals').then(rows=>$('#leaderboard').innerHTML=rows.length?rows.map(r=>`<p>Citizen ${esc(r.handle)} · ${r.referrals} referrals</p>`).join(''):'<p>The first neighbours are still arriving.</p>');
if(new URLSearchParams(location.search).has('checkout'))toast(new URLSearchParams(location.search).get('checkout')==='success'?'Checkout returned successfully. Your purchase will appear after the verified webhook arrives.':'Checkout cancelled. No new benefits were activated.');
