import {api,esc,toast} from './common.js';
import {hydrateLpcPreviews} from './lpc-renderer.js';
export async function characterPicker(refresh,onControl){
 const state=await api('/api/characters'),dialog=document.createElement('dialog');dialog.className='citizenship-dialog';let selected=null,query='',browsing=false;const current=state.characters.find(c=>c.id===state.selected)||state.characters[0];
 const avatar=n=>n.appearance?.system==='lpc'?`<div class="resident-avatar"><canvas width="100" height="100" data-lpc-preview="${esc(JSON.stringify(n.appearance))}" aria-hidden="true"></canvas></div>`:`<div class="resident-avatar"><img src="/assets/dreamland/Character_${String(n.avatar||1).padStart(3,'0')}.png" alt="" /></div>`;
 function paint(){dialog.innerHTML=`<button class="close" aria-label="Close">×</button><span class="eyebrow">Everwick · Moving day</span><div class="arrival-steps"><span>01 Account</span><span class="current">02 Your citizen</span><span>03 Open Story</span></div><h2>${selected?'Your next chapter<br>starts here.':'Someone here<br>could be you.'}</h2><p>${current?.starter?'Your free starter can work, follow Story, own a home or business, and explore dungeons. This citizen cannot breed or transfer.':'A continuing life: work, possessions and relationships stay with your citizen.'}</p><div class="citizenship-summary"><span>${state.population} residents</span><span>One continuing life</span><span>${current?.starter?'Free starter · Generation S':`${state.slotsRemaining||0} paid claim slots remaining`}</span></div>${state.selected&&!browsing?`<h3>${esc(current?.name||'Your citizen')}</h3><p>WASD / click or use the touch arrows to take control, then open Story for the clinic delivery.</p><button id="returnLife">Return to my life →</button>${state.canClaim&&state.slotsRemaining>0?'<button id="browseClaims" class="secondary">Use a paid Generation A claim slot →</button>':''}`:selected?`<div class="arrival-profile">${avatar(selected)}<span class="eyebrow">${esc(selected.occupation)} · ${selected.age}</span><h3>${esc(selected.name)}</h3><p>${esc(selected.persona?.description||selected.personality)}</p><blockquote>${esc(selected.goal)}</blockquote><p>${selected.cash} ◈ savings · Generation ${esc(selected.generationLabel||'A')} Founder</p><p>This is your persistent citizen. Open Story after arriving to find the town clerk, take a delivery job and work toward a home.</p><div class="actions"><button id="confirmResident">Begin this life →</button><button class="secondary" id="backResidents">Meet someone else</button></div></div>`:`${!state.canClaim?'<p class="memory">No Generation A claim slots available. Alpha play includes a free starter.</p><a href="/#founders">View optional packs and sales status</a>':''}<label class="field">Find a neighbour<input id="residentSearch" type="text" placeholder="Name, work or personality" value="${esc(query)}"></label><p id="residentCount" role="status"></p><div class="resident-grid" id="residentResults"></div>`}<p class="form-error" role="alert"></p>`;
 dialog.querySelector('.close').onclick=()=>dialog.close();const error=e=>dialog.querySelector('.form-error').textContent=e.message;
 dialog.querySelector('#returnLife')?.addEventListener('click',async e=>{e.target.disabled=true;try{if(onControl)await onControl();else{await api('/api/control',{});await refresh();}dialog.close();document.querySelector('#town')?.focus();}catch(err){error(err);e.target.disabled=false;}});
 dialog.querySelector('#browseClaims')?.addEventListener('click',()=>{browsing=true;paint();});
 dialog.querySelector('#backResidents')?.addEventListener('click',()=>{selected=null;paint();});
 dialog.querySelector('#confirmResident')?.addEventListener('click',async e=>{e.target.disabled=true;try{await api('/api/command',{action:'claim-citizen',data:{citizen:selected.id}});await refresh();if(onControl)await onControl({silent:true});else{await api('/api/control',{});await refresh();}dialog.close();toast("You’re in. WASD / click or touch arrows to move, then open Story.");document.querySelector('#town')?.focus();}catch(err){error(err);e.target.disabled=false;}});
 hydrateLpcPreviews(dialog);
 function results(){const list=state.residents.filter(n=>`${n.name} ${n.occupation} ${n.personality}`.toLowerCase().includes(query.toLowerCase()));dialog.querySelector('#residentCount').textContent=`${list.length} available Generation A founders`;dialog.querySelector('#residentResults').innerHTML=list.map(n=>`<article class="resident-card">${avatar(n)}<span class="eyebrow">${esc(n.occupation)} · ${n.age}</span><h3>${esc(n.name)}</h3><p>${esc(n.persona?.description||n.personality)}</p><p class="resident-goal">${esc(n.goal)}</p><p class="muted">${n.cash} ◈ savings</p><button data-resident="${esc(n.id)}" ${state.canClaim?'':'disabled'}>Meet ${esc(n.name.split(' ')[0])} →</button></article>`).join('')||'<p>No residents match. Try another name or occupation.</p>';dialog.querySelectorAll('[data-resident]').forEach(b=>b.onclick=()=>{selected=state.residents.find(n=>n.id===b.dataset.resident);paint();dialog.scrollTop=0;dialog.querySelector('#confirmResident').focus();});hydrateLpcPreviews(dialog);}
 if((!state.selected||browsing)&&!selected){results();dialog.querySelector('#residentSearch').oninput=e=>{query=e.target.value;results();};}}
 document.body.append(dialog);paint();dialog.showModal();dialog.onclose=()=>dialog.remove();
}