import {esc,money} from './common.js';
import {FURNITURE} from './furniture.js';
export function propertyPanel(w,me,selected){
 const inside=w.properties.find(p=>p.id===w.player.insideHouse);
 if(inside&&inside.owner!==me.user.id)return `<span class="eyebrow">Visiting a neighbour</span><h2>${esc(inside.name)}</h2><p>Home of ${esc(inside.ownerName||'your neighbour')}. Walk around with WASD. Only the owner can decorate.</p><button data-house-exit>Return outside</button>`;
 if(inside)return `<span class="eyebrow">Your home</span><h2>${esc(inside.name)}</h2><button data-house-exit>Return outside</button><p>Drag furniture inside the room to move it. Drag a storage item from this panel, or select Place then click the room. Hold the item and press R to rotate. Escape cancels. The doorway must stay clear.</p><h3>Your furniture</h3>${inside.interior.furniture.map(i=>`<form class="business-card" data-place-form="${i.id}"><button type="button" draggable="true" data-furniture-place="${i.id}">Place / drag ${esc(i.kind)}</button><strong>${esc(i.kind)}</strong> · ${i.x===null?'In storage':`${i.x}, ${i.y}`}<label class="field">X<input name="x" type="number" min="1" max="10" value="${i.x??2}" required></label><label class="field">Y<input name="y" type="number" min="1" max="8" value="${i.y??2}" required></label><label class="field">Rotation<select name="rotation">${[0,1,2,3].map(r=>`<option value="${r}" ${r===i.rotation?'selected':''}>${r*90}°</option>`).join('')}</select></label><button class="small">Place / move</button><button type="button" class="small secondary" data-store="${i.id}">Store</button></form>`).join('')||'<p>No furniture yet.</p>'}<h3>Furniture shop</h3>${Object.entries(FURNITURE).map(([k,f])=>`<p>${esc(k)} <button class="small" data-furniture-buy="${k}">Buy · ${f.price} ◈</button></p>`).join('')}`;
 const visits=w.properties.filter(p=>p.visitable&&p.owner!==me.user.id);
 const owned=w.properties.filter(p=>p.owner===me.user.id),offers=w.properties.filter(p=>p.forSale&&p.owner!==me.user.id).sort((a,b)=>Number(!!a.tenant)-Number(!!b.tenant)||a.valuation-b.valuation);
 const card=(p,isOwned)=>{const n=w.npcs.find(n=>n.id===p.tenant);return `<article class="business-card"><strong>${esc(p.name)}</strong><p>${n?`Tenant: ${esc(n.name)} · Daily rent ${p.rent} ◈`:'Private cottage · Furnishable interior'}</p>${isOwned?`<button data-house-enter="${p.id}">Enter & decorate</button>${n?`<form data-rent-form="${p.id}"><label class="field">Daily rent<input type="number" name="rent" min="10" max="100" value="${p.rent}" required></label><button class="small">Save rent</button></form>`:''}`:`<button data-property-buy="${p.id}" ${w.player.cash<p.valuation?'disabled':''}>Buy · ${money(p.valuation)} ◈</button>${w.player.cash<p.valuation?`<p class="muted">You have ${money(w.player.cash)} ◈ · Need ${money(p.valuation-w.player.cash)} more. Follow Story or earn wages and delivery rewards.</p>`:''}`}</article>`;};
 return `<span class="eyebrow">A place to call home</span><h2>Homes of Everwick.</h2>${selected?`<p class="memory">Selected: ${esc(w.properties.find(p=>p.id===selected)?.name||'home')}</p>`:''}<h3>Visit your neighbours</h3>${visits.map(p=>`<article class="business-card"><strong>${esc(p.name)}</strong><p>Home of ${esc(p.ownerName)}</p><button data-house-visit="${p.id}">Visit home</button></article>`).join('')||'<p>No neighbour-owned homes yet.</p>'}<h3>Your properties</h3>${owned.map(p=>card(p,true)).join('')||'<p>You do not own a home yet.</p>'}<h3>On the market</h3><p class="muted">Start with Story’s clinic delivery, then look for a starter home around 900 ◈. Lowest-priced vacant homes appear first.</p>${offers.map(p=>card(p,false)).join('')}`;
}
