import test from 'node:test';
import assert from 'node:assert/strict';
import {seedWorld,transfer} from '../server/simulation.mjs';
import {bindCitizens} from '../server/citizenship.mjs';
import {generateDungeon,dungeonCommand} from '../server/dungeon.mjs';
import {DUNGEON_ENTRANCE} from '../client/world-map.js';

function reachable(run){const seen=new Set(['1,1']),q=[{x:1,y:1}];for(let i=0;i<q.length;i++){const p=q[i];for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=p.x+dx,y=p.y+dy,k=`${x},${y}`;if(run.map[y]?.[x]!=='.'||seen.has(k))continue;seen.add(k);q.push({x,y});}}return seen;}
function controlledWorld(){const w=seedWorld(1000),n=w.npcs[0],p={id:'user',name:'Explorer',accountName:'Explorer',citizenshipAccount:true,onboarded:true,citizenId:n.id,ownedCitizenIds:[n.id],created:0,lastSeen:0,controlAt:Date.now(),presenceAt:Date.now(),positionAt:Date.now(),x:DUNGEON_ENTRANCE.x,y:DUNGEON_ENTRANCE.y,inventory:{},cash:0};w.players[p.id]=p;n.ownerId=p.id;n.controllerId=p.id;bindCitizens(w);p.x=DUNGEON_ENTRANCE.x;p.y=DUNGEON_ENTRANCE.y;p.controlAt=p.presenceAt=Date.now();return {w,p,n};}
function dirTo(a,b){if(b.x>a.x)return 'east';if(b.x<a.x)return 'west';if(b.y>a.y)return 'south';return 'north';}
function adjacentFloor(run){return [[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:run.position.x+dx,y:run.position.y+dy})).find(q=>run.map[q.y]?.[q.x]==='.');}

 test('procedural dungeon seeds are different and every objective is reachable',()=>{const a=generateDungeon('alpha'),b=generateDungeon('beta');assert.notDeepEqual(a.map,b.map);for(const run of [a,b]){const seen=reachable(run);assert.ok(seen.has(`${run.exit.x},${run.exit.y}`));assert.equal(run.seals.length,3);for(const seal of run.seals)assert.ok(seen.has(`${seal.x},${seal.y}`));assert.ok(run.relic);assert.ok(seen.has(`${run.relic.x},${run.relic.y}`));assert.equal(run.shrines.length,2);for(const shrine of run.shrines)assert.ok(seen.has(`${shrine.x},${shrine.y}`));}});

test('only a directly controlled player citizen can enter',()=>{const {w,p}=controlledWorld();p.controlAt=0;p.presenceAt=0;assert.throws(()=>dungeonCommand(w,p,'dungeon-enter',{}, {transfer}),/direct control/i);p.controlAt=p.presenceAt=Date.now();const run=dungeonCommand(w,p,'dungeon-enter',{}, {transfer});assert.equal(run.active,true);assert.equal(p.dungeonStats.runs,1);});

test('death ends the run and takes a real penalty',()=>{const {w,p}=controlledWorld();p.cash=1000;p.inventory={food:2};dungeonCommand(w,p,'dungeon-enter',{}, {transfer});const run=p.dungeonRun,adj=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:run.position.x+dx,y:run.position.y+dy})).find(q=>run.map[q.y]?.[q.x]==='.');assert.ok(adj);run.enemies=[];run.caches=[];run.traps=[{x:adj.x,y:adj.y,damage:50,triggered:false}];run.health=1;const beforeCash=p.cash;dungeonCommand(w,p,'dungeon-move',{dir:dirTo(run.position,adj)}, {transfer});assert.equal(p.dungeonRun,null);assert.equal(p.lastDungeonResult.status,'death');assert.ok(p.cash<beforeCash);assert.equal(p.inventory.food,1);assert.equal(p.x,DUNGEON_ENTRANCE.x);});

test('shrine rooms and relic vaults change the active expedition',()=>{const {w,p}=controlledWorld();dungeonCommand(w,p,'dungeon-enter',{}, {transfer});const run=p.dungeonRun,adj=adjacentFloor(run);assert.ok(adj);run.enemies=[];run.traps=[];run.caches=[];run.shrines=[{kind:'mending',x:adj.x,y:adj.y,used:false}];run.relic={x:adj.x,y:adj.y,claimed:false};run.health=40;dungeonCommand(w,p,'dungeon-move',{dir:dirTo(run.position,adj)}, {transfer});assert.equal(run.shrines[0].used,true);assert.equal(run.relic.claimed,true);assert.ok(run.health>40);assert.ok(run.log.some(x=>/relic vault/i.test(x)));});

test('wayfinder shrines reveal a remaining objective',()=>{const {w,p}=controlledWorld();dungeonCommand(w,p,'dungeon-enter',{}, {transfer});const run=p.dungeonRun,adj=adjacentFloor(run),target=run.seals.find(s=>!run.discovered.includes(`${s.x},${s.y}`))||run.seals[0];assert.ok(adj);assert.ok(target);run.enemies=[];run.traps=[];run.caches=[];run.relic=null;run.seals=[{...target,taken:false}];run.shrines=[{kind:'wayfinder',x:adj.x,y:adj.y,used:false}];dungeonCommand(w,p,'dungeon-move',{dir:dirTo(run.position,adj)}, {transfer});assert.equal(run.shrines[0].used,true);assert.ok(run.discovered.includes(`${target.x},${target.y}`));});

test('dungeon-move returns the live run so clients can patch without a full world reload',()=>{const {w,p}=controlledWorld();dungeonCommand(w,p,'dungeon-enter',{}, {transfer});const before=p.dungeonRun.discovered.length,adj=adjacentFloor(p.dungeonRun);assert.ok(adj);p.dungeonRun.enemies=[];p.dungeonRun.traps=[];p.dungeonRun.caches=[];const result=dungeonCommand(w,p,'dungeon-move',{dir:dirTo(p.dungeonRun.position,adj)}, {transfer});assert.equal(result,p.dungeonRun);assert.equal(result.active,true);assert.deepEqual(result.position,adj);assert.ok(result.discovered.length>=before);});

test('solving three seals and reaching the exit pays conserved coins and produced loot',()=>{const {w,p}=controlledWorld();p.cash=600;dungeonCommand(w,p,'dungeon-enter',{}, {transfer});const run=p.dungeonRun;for(const seal of run.seals)seal.taken=true;run.enemies=[];run.traps=[];run.caches=[];run.relic={x:run.position.x,y:run.position.y,claimed:true};const neighbor=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:run.exit.x+dx,y:run.exit.y+dy})).find(q=>run.map[q.y]?.[q.x]==='.');assert.ok(neighbor);run.position=neighbor;const beforeCash=p.cash,beforeTreasury=w.treasury.cash,beforeProduced=w.produced.ore||0;dungeonCommand(w,p,'dungeon-move',{dir:dirTo(neighbor,run.exit)}, {transfer});assert.equal(p.dungeonRun,null);assert.equal(p.lastDungeonResult.status,'success');assert.ok(p.cash>beforeCash);assert.equal(beforeTreasury-w.treasury.cash,p.lastDungeonResult.reward.coins);assert.equal((w.produced.ore||0)-beforeProduced,p.lastDungeonResult.reward.ore);assert.ok((p.inventory.ore||0)>=p.lastDungeonResult.reward.ore);assert.equal(p.lastDungeonResult.reward.artifact,1);assert.equal(p.inventory.artifact,1);});
