import test from 'node:test';import assert from 'node:assert/strict';
import {seedWorld,addPlayer,command,totalCash,trade} from '../server/simulation.mjs';
import {advanceMovement} from '../server/movement.mjs';
import {MAP,PLACES,blocked} from '../client/world-map.js';
test('all workplaces have reachable walkable entrances in the expanded map',()=>{assert.ok(MAP.width>28);for(const b of Object.values(PLACES)){assert.equal(blocked(b.x+1,b.y+1),false);assert.equal(blocked(b.x+2,b.y+2),false);}});
test('citizens move between economic ticks and travel at bounded speed',()=>{const w=seedWorld();w.tick=8;const before=w.npcs.map(n=>({x:n.x,y:n.y}));advanceMovement(w,.2);const moved=w.npcs.filter((n,i)=>Math.hypot(n.x-before[i].x,n.y-before[i].y)>0);assert.ok(moved.length>w.npcs.length*.5);for(let i=0;i<w.npcs.length;i++){const n=w.npcs[i];assert.ok(Math.hypot(n.x-before[i].x,n.y-before[i].y)<=.4);assert.ok(!blocked(Math.round(n.x),Math.round(n.y)));}assert.equal(w.tick,8);});
test('citizens reach work sites through pathfinding',()=>{const w=seedWorld();w.tick=8;for(let i=0;i<300;i++)advanceMovement(w,.2);const arrived=w.npcs.filter(n=>{const b=w.businesses.find(b=>b.id===n.employer);return Math.hypot(n.x-(b.x+2),n.y-(b.y+1))<5;});assert.ok(arrived.length>=w.npcs.length*.9,`${arrived.length} arrived`);});
test('buy and sell loop moves actual goods and conserves cash',()=>{const w=seedWorld();addPlayer(w,'p','Trader');const initial=totalCash(w);const farm=w.businesses.find(b=>b.id==='sunfield');command(w,'p','buy-item',{id:farm.id,qty:3});assert.equal(w.players.p.inventory.food,3);const result=command(w,'p','sell-item',{id:'restaurant',item:'food',qty:2});assert.equal(w.players.p.inventory.food,1);assert.equal(result.received,Math.floor(w.prices.food*.8)*2);assert.equal(totalCash(w),initial);assert.throws(()=>command(w,'p','sell-item',{id:'restaurant',item:'ore',qty:1}));assert.throws(()=>command(w,'p','sell-item',{id:'restaurant',item:'food',qty:5}));});
test('property purchase and rent controls require ownership',()=>{const w=seedWorld();addPlayer(w,'p','Landlord');addPlayer(w,'q','Other');const initial=totalCash(w);command(w,'p','buy-property',{id:'home-0'});assert.equal(w.properties[0].owner,'p');assert.equal(totalCash(w),initial);assert.throws(()=>command(w,'q','set-rent',{id:'home-0',rent:70}));command(w,'p','set-rent',{id:'home-0',rent:50});assert.equal(w.npcs[0].rent,50);assert.ok(w.npcs[0].relationships.p<0);});
