import {claimResident} from '../server/citizenship.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {database,mutate} from '../server/db.mjs';import {createApp} from '../server/index.mjs';import {visiblePlayers} from '../server/presence.mjs';
test('two accounts see presence and house ownership, share rooms, and cannot decorate another home',async t=>{const db=database(':memory:'),server=createApp(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.close();db.close();});const base=`http://127.0.0.1:${server.address().port}`;
 const request=async(cookie,path,body)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Origin:'http://localhost:3100',Cookie:cookie,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const a=await request('','/api/auth/register',{name:'Alice',email:'a@example.com',password:'a testing password'}),b=await request('','/api/auth/register',{name:'Bryn',email:'b@example.com',password:'a testing password'});assert.equal(a.status,201);assert.equal(b.status,201);
 mutate(db,w=>{for(const [i,id]of [a.data.id,b.data.id].entries()){const p=w.players[id];claimResident(w,p,`npc-${20+i}`,{legacy:true});w.treasury.cash-=4500-p.cash;p.cash=4500;}});
 for(const c of [a.cookie,b.cookie]){const w=(await request(c,'/api/world')).data;assert.equal((await request(c,'/api/position',{x:w.player.x,y:w.player.y})).status,200);}
 let motion=(await request(a.cookie,'/api/motion')).data;assert.equal(motion.players.length,2);assert.deepEqual(motion.players.map(p=>p.name).sort(),['Mara Moss','Theo Moss']);assert.ok(motion.players.every(p=>!('cash'in p)&&!('email'in p)));assert.equal((await request('','/api/motion')).data.players.length,0);
 const cmd=(c,action,data={})=>request(c,'/api/command',{action,data});assert.equal((await cmd(a.cookie,'buy-property',{id:'cottage-1'})).status,200);const house=(await request(b.cookie,'/api/world')).data.properties.find(h=>h.id==='cottage-1');assert.equal(house.ownerName,'Mara Moss');assert.equal(house.mapBuilding,'cottage-1');assert.equal(house.visitable,true);
 assert.equal((await cmd(a.cookie,'enter-house',{id:'cottage-1'})).status,200);assert.equal((await cmd(b.cookie,'visit-house',{id:'cottage-1'})).status,200);assert.equal((await cmd(b.cookie,'buy-furniture',{id:'cottage-1',kind:'chair',version:0})).status,400);
 for(const c of [a.cookie,b.cookie])assert.equal((await request(c,'/api/position',{x:5.7,y:8})).status,200);motion=(await request(a.cookie,'/api/motion')).data;assert.ok(motion.players.every(p=>p.insideHouse==='cottage-1'));assert.equal((await request(b.cookie,'/api/position',{x:0,y:0})).status,400);assert.equal((await cmd(b.cookie,'exit-house')).status,200);assert.equal((await cmd(b.cookie,'visit-house',{id:'cottage-2'})).status,400);
 });
test('disconnected players expire from shared presence',()=>{const w={players:{a:{id:'a',name:'A',presenceAt:1000,x:1,y:2}}};assert.equal(visiblePlayers(w,14000).length,1);assert.equal(visiblePlayers(w,17000).length,0);});
