import {BLUEPRINTS,PARCELS} from '../client/construction.js';
export function ensureConstruction(w){return w.construction??={nextId:1,projects:[]};}
export function materialsReady(p){return Object.entries(BLUEPRINTS[p.kind].materials).every(([k,v])=>(p.materials[k]||0)>=v);}
export function constructionCommand(w,p,action,data,transfer){const sites=ensureConstruction(w);
 if(action==='plan-building'){if(!Object.hasOwn(BLUEPRINTS,data.kind))throw Error('Unknown blueprint');const parcel=PARCELS.find(x=>x.id===data.parcel),spec=BLUEPRINTS[data.kind];if(!parcel||sites.projects.some(s=>s.parcel===parcel.id))throw Error('This parcel is unavailable');if(p.cash<spec.permit+100+spec.capital)throw Error('Not enough coins to fund construction');const site={id:`construction-${sites.nextId++}`,parcel:parcel.id,kind:data.kind,name:spec.name+' '+parcel.id.slice(7),x:parcel.x,y:parcel.y,owner:p.id,status:'building',materials:{},work:0,cash:0,credits:{}};sites.projects.push(site);transfer(w,p.id,'treasury',spec.permit,'construction-permit');transfer(w,p.id,site.id,100+spec.capital,'construction-fund');return site;}
 if(action==='stop-building'){p.building=null;return p;}
 const site=sites.projects.find(s=>s.id===data.id&&s.status==='building');if(!site)throw Error('This construction site is unavailable');if(p.insideHouse||Math.hypot(p.x-site.x-2,p.y-site.y-1)>3)throw Error('Walk to the site first');
 if(action==='deliver-building'){let delivered=0;for(const [item,need]of Object.entries(BLUEPRINTS[site.kind].materials)){const qty=Math.min(need-(site.materials[item]||0),p.inventory[item]||0);if(qty>0){p.inventory[item]-=qty;site.materials[item]=(site.materials[item]||0)+qty;delivered+=qty;}}if(!delivered)throw Error('Your satchel has no materials still needed by this site');return site;}
 if(action==='work-building'){if(!materialsReady(site))throw Error('Deliver all required materials before building');p.building=site.id;return site;}throw Error('Unknown construction action');
}
function finish(w,site){const spec=BLUEPRINTS[site.kind];for(const [k,v]of Object.entries(site.materials))w.consumed[k]=(w.consumed[k]||0)+v;site.materials={};site.status='complete';site.finishedTick=w.tick;for(const player of Object.values(w.players))if(player.building===site.id)player.building=null;
 if(site.kind==='cottage'){w.properties.push({id:site.id,name:site.name,x:site.x,y:site.y,kind:'residence',mapBuilding:site.parcel,owner:site.owner,tenant:null,rent:0,forSale:false,valuation:2400,interior:{version:0,nextId:1,furniture:[],floor:'oak',wall:'cream'}});}
 else{const garden=site.kind==='garden',capital=spec.capital;w.businesses.push({id:site.id,name:site.name,x:site.x,y:site.y,type:garden?'Farm':'Store',output:garden?'food':'goods',recipe:garden?{}:{food:1},rate:garden?4:1,price:garden?12:42,wage:40,cash:capital,inventory:{},owner:site.owner,employees:[],forSale:false,valuation:3600,revenue:0,expenses:0,lastProfit:0,arrears:0,status:'open',hours:12,advertising:0,upgrade:0});site.cash-=capital;}
 w.players[site.owner].cash+=site.cash;site.cash=0;w.events.push({id:w.nextEvent++,tick:w.tick,type:'construction',title:site.name+' opens',body:'Local builders completed a new building in the expansion district.',subjects:[site.owner,site.id]});
}
export function advanceConstruction(w,seconds){for(const site of w.construction?.projects||[]){if(site.status!=='building'||!materialsReady(site))continue;const spec=BLUEPRINTS[site.kind];const workers=[...w.npcs.filter(n=>n.residency!=='away'&&n.brain?.task?.place===site.id&&n.activity==='build'),...Object.values(w.players).filter(p=>p.building===site.id&&!p.insideHouse&&Date.now()-(p.presenceAt||0)<15000)];for(const n of workers){if(Math.hypot(n.x-site.x-2,n.y-site.y-1)>4)continue;const work=Math.min(spec.work-site.work,seconds*(1+(n.skills?.craft||1)*.08));if(work<=0)break;site.work+=work;const c=site.credits[n.id]??={work:0,paid:0};c.work+=work;const wage=Math.floor(c.work/5)-c.paid;if(wage&&site.cash-spec.capital>=wage){site.cash-=wage;n.cash+=wage;c.paid+=wage;w.ledger.push({tick:w.tick,from:site.id,to:n.id,amount:wage,reason:'builder-wage'});}n.buildingExperience=(n.buildingExperience||0)+work;}if(site.work>=spec.work)finish(w,site);}}
