import {FARM_PLOTS,season} from '../client/farming.js';
export function ensureFarms(w){w.farmPlots??=FARM_PLOTS.map(p=>({...p,owner:null,fertility:100,crop:null}));return w.farmPlots;}
export function farmingCommand(w,p,data,transfer){const plots=ensureFarms(w),plot=plots.find(x=>x.id===data.id);if(!plot)throw Error('Unknown farm plot');if(p.insideHouse||Math.hypot(p.x-plot.x,p.y-plot.y)>3)throw Error('Walk to this farm plot first');
 if(data.kind==='lease'){if(plot.owner)throw Error('This plot is already leased');if(plots.filter(x=>x.owner===p.id).length>=2)throw Error('Each player can lease two plots');if(!transfer(w,p.id,'treasury',100,'farm-lease'))throw Error('You need 100 coins');plot.owner=p.id;return plot;}
 if(plot.owner!==p.id)throw Error('You do not lease this plot');
 if(data.kind==='plant'){if(plot.crop)throw Error('A crop is already growing');if(plot.fertility<25)throw Error('Compost the soil before planting');if(!(p.inventory.food>0)||p.cash<3)throw Error('Planting requires one food seed and 3 coins');transfer(w,p.id,'treasury',3,'crop-seed-supplies');p.inventory.food--;w.consumed.food=(w.consumed.food||0)+1;plot.crop={ready:w.tick+4,watered:0,lastWater:-1,season:season(w)};return plot;}
 if(data.kind==='water'){if(!plot.crop)throw Error('Plant first');if(plot.crop.lastWater===w.tick)throw Error('The soil is already watered this town hour');if(plot.crop.watered>=2)throw Error('The crop has enough water');plot.crop.watered++;plot.crop.lastWater=w.tick;return plot;}
 if(data.kind==='compost'){if(plot.fertility>=100)throw Error('The soil is already fertile');if(!(p.inventory.food>0))throw Error('You need one food item for compost');p.inventory.food--;w.consumed.food=(w.consumed.food||0)+1;plot.fertility=Math.min(100,plot.fertility+50);return plot;}
 if(data.kind==='harvest'){const crop=plot.crop;if(!crop||w.tick<crop.ready||crop.watered<(w.city?.level?1:2))throw Error('The crop needs time and sufficient water');const qty=({Spring:4,Summer:4,Autumn:5,Winter:2})[crop.season];p.inventory.food=(p.inventory.food||0)+qty;w.produced.food=(w.produced.food||0)+qty;plot.fertility-=25;plot.crop=null;p.farmingXp=(p.farmingXp||0)+10;return {harvest:qty};}
 throw Error('Unknown farming action');}
