import {RECIPES,ITEMS} from '../client/industry.js';
const near=(p,b)=>{if(p.insideHouse||Math.hypot(p.x-b.x-2,p.y-b.y-1)>3)throw Error('Walk to the workshop first');};
export function ensureExchange(w){return w.exchange??={nextId:1,listings:[],sales:[]};}
export function buyListing(w,buyer,id,qty,transfer){const ex=ensureExchange(w),l=ex.listings.find(l=>l.id===id);if(!l||l.seller===buyer.id||!Number.isSafeInteger(qty)||qty<1||qty>l.qty)throw Error('This listing or quantity is unavailable');const total=l.price*qty,fee=Math.ceil(total*.02);if(buyer.cash<total)throw Error('Not enough coins');transfer(w,buyer.id,l.seller,total-fee,'player-market:'+l.item);transfer(w,buyer.id,'treasury',fee,'market-sales-tax');ex.taxCollected=(ex.taxCollected||0)+fee;ex.unspentTax=(ex.unspentTax||0)+fee;buyer.inventory[l.item]=(buyer.inventory[l.item]||0)+qty;l.qty-=qty;ex.sales.push({tick:w.tick,item:l.item,qty,price:l.price,fee,buyerType:w.players[buyer.id]?'player':'npc'});ex.sales=ex.sales.slice(-200);if(!l.qty)ex.listings=ex.listings.filter(x=>x.id!==l.id);return buyer.inventory;}
export function industryCommand(w,p,action,data,transfer){const ex=ensureExchange(w);
 if(action==='list-goods'){if(!ITEMS.includes(data.item)||!Number.isSafeInteger(data.qty)||data.qty<1||data.qty>50||!Number.isSafeInteger(data.price)||data.price<1||data.price>1000)throw Error('Invalid item, quantity or price');if(ex.listings.filter(l=>l.seller===p.id).length>=10)throw Error('You can have ten active listings');if((p.inventory[data.item]||0)<data.qty)throw Error('Not enough goods');p.inventory[data.item]-=data.qty;const l={id:`listing-${ex.nextId++}`,seller:p.id,sellerName:p.name,item:data.item,qty:data.qty,price:data.price};ex.listings.push(l);return l;}
 if(action==='buy-listing')return buyListing(w,p,data.id,data.qty,transfer);
 if(action==='cancel-listing'){const l=ex.listings.find(l=>l.id===data.id&&l.seller===p.id);if(!l)throw Error('You do not own this listing');p.inventory[l.item]=(p.inventory[l.item]||0)+l.qty;ex.listings=ex.listings.filter(x=>x.id!==l.id);return p.inventory;}
 if(action==='craft'){if(p.crafting)throw Error('Collect your current production first');if(!Object.hasOwn(RECIPES,data.recipe)||!Number.isSafeInteger(data.qty)||data.qty<1||data.qty>5)throw Error('Invalid recipe or quantity');const r=RECIPES[data.recipe],b=w.businesses.find(b=>b.id===r.station);near(p,b);if(b.status!=='open')throw Error('This workshop is closed');for(const [k,v]of Object.entries(r.inputs))if((p.inventory[k]||0)<v*data.qty)throw Error('Buy the required materials first');if(!transfer(w,p.id,b.id,r.fee*data.qty,'crafting-fee'))throw Error('Not enough coins for workshop fees');b.revenue+=r.fee*data.qty;for(const [k,v]of Object.entries(r.inputs)){p.inventory[k]-=v*data.qty;w.consumed[k]=(w.consumed[k]||0)+v*data.qty;}p.crafting={recipe:data.recipe,qty:data.qty,station:r.station,ends:w.tick+r.hours*data.qty};return p.crafting;}
 if(action==='collect-craft'){const j=p.crafting;if(!j||w.tick<j.ends)throw Error('Production is not ready');near(p,w.businesses.find(b=>b.id===j.station));const r=RECIPES[j.recipe];p.inventory[r.output]=(p.inventory[r.output]||0)+j.qty;w.produced[r.output]=(w.produced[r.output]||0)+j.qty;p.crafting=null;return p.inventory;}
 throw Error('Unknown industry action');
}
export function feedFromMarket(w,n,transfer){if(Math.hypot(n.x-35,n.y-29)>5)return false;const l=ensureExchange(w).listings.filter(l=>l.item==='food'&&l.price<=n.preferences.maxFoodPrice&&l.price<=n.cash).sort((a,b)=>a.price-b.price)[0];if(!l)return false;buyListing(w,n,l.id,1,transfer);return true;}

export function votePolicy(w,p,policy){if(!['reserve','infrastructure','relief'].includes(policy))throw Error('Unknown town policy');w.policyBallot??={day:Math.floor(w.tick/24),votes:{}};if(w.policyBallot.day!==Math.floor(w.tick/24))w.policyBallot={day:Math.floor(w.tick/24),votes:{}};w.policyBallot.votes[p.id]=policy;return {policy};}
export function civicEconomy(w){const ex=ensureExchange(w),votes={reserve:0,infrastructure:0,relief:0};for(const v of Object.values(w.policyBallot?.votes||{}))votes[v]++;return {policy:w.marketPolicy||'reserve',votes,collected:ex.taxCollected||0,reserve:ex.unspentTax||0,lastReport:w.policyReport||null};}
export function settlePolicy(w,transfer,event){const ex=ensureExchange(w),counts=civicEconomy(w).votes,max=Math.max(...Object.values(counts));if(max){const winners=Object.keys(counts).filter(k=>counts[k]===max);w.marketPolicy=winners.length===1?winners[0]:'reserve';}w.policyBallot={day:Math.floor(w.tick/24),votes:{}};const budget=Math.min(ex.unspentTax||0,w.treasury.cash);let spent=0,people=0;
 if(w.marketPolicy==='relief'){for(const n of w.npcs.filter(n=>n.residency!=='away'&&n.needs.hunger>60&&n.cash<w.prices.food*2).sort((a,b)=>a.cash-b.cash)){const amount=Math.min(budget-spent,w.prices.food*2-n.cash);if(amount<=0)break;if(transfer(w,'treasury',n.id,amount,'market-funded-food-relief')){spent+=amount;people++;}}}
 if(w.marketPolicy==='infrastructure'){w.city??={fund:0,level:0};if(w.city.level<3){spent=Math.min(budget,(3-w.city.level)*2000-w.city.fund);w.city.fund+=spent;while(w.city.fund>=2000&&w.city.level<3){w.city.fund-=2000;w.city.level++;}}}
 ex.unspentTax=Math.max(0,(ex.unspentTax||0)-spent);w.policyReport={day:Math.floor(w.tick/24),policy:w.marketPolicy||'reserve',allocated:spent,people};if(spent)event(w,'community','Player market funds town services',`${spent} coins in collected market fees funded ${w.marketPolicy==='relief'?`food assistance for ${people} residents`:'infrastructure'}.`);}
