import {createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
import {atomic,audit,mutate,readWorld,saveWorld} from './db.mjs';
import {hashPassword,randomId,requireAdmin,requireUser,tokenHash} from './auth.mjs';

const B32='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function toBase32(buf){let bits=0,val=0,out='';for(const b of buf){val=(val<<8)|b;bits+=8;while(bits>=5){out+=B32[(val>>>(bits-5))&31];bits-=5;}}if(bits)out+=B32[(val<<(5-bits))&31];return out;}
function fromBase32(str){const clean=String(str||'').toUpperCase().replace(/=+$/,'').replace(/[^A-Z2-7]/g,'');let bits=0,val=0;const out=[];for(const ch of clean){const idx=B32.indexOf(ch);if(idx<0)continue;val=(val<<5)|idx;bits+=5;if(bits>=8){out.push((val>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
export function generateMfaSecret(){return toBase32(randomBytes(20));}
export function totpCode(secret,step=Math.floor(Date.now()/30000)){const key=fromBase32(secret);if(key.length<10)throw Error('Invalid MFA secret');const msg=Buffer.alloc(8);msg.writeUInt32BE(Math.floor(step/0x100000000),0);msg.writeUInt32BE(step>>>0,4);const h=createHmac('sha1',key).update(msg).digest();const o=h[19]&0xf;const n=((h[o]&0x7f)<<24)|(h[o+1]<<16)|(h[o+2]<<8)|h[o+3];return String(n%1000000).padStart(6,'0');}
export function verifyTotp(secret,code,window=1){const c=String(code||'').replace(/\s/g,'');if(!/^\d{6}$/.test(c))return false;const now=Math.floor(Date.now()/30000);for(let i=-window;i<=window;i++){const expected=Buffer.from(totpCode(secret,now+i));const got=Buffer.from(c);if(expected.length===got.length&&timingSafeEqual(expected,got))return true;}return false;}

export function salesEnabled(db){const row=db.prepare("SELECT value FROM ops WHERE key='sales_enabled'").get();return !row||row.value!=='0';}
export function setSalesEnabled(db,userId,enabled){db.prepare("INSERT INTO ops(key,value) VALUES('sales_enabled',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(enabled?'1':'0');audit(db,userId,enabled?'sales-resume':'sales-shutdown',{sales_enabled:!!enabled});return {sales_enabled:!!enabled};}

export function mfaStatus(db,userId){const row=db.prepare('SELECT enabled,confirmed_at FROM user_mfa WHERE user_id=?').get(userId);return {enabled:!!row?.enabled,confirmed_at:row?.confirmed_at||null};}
export function beginMfaSetup(db,user){requireAdmin(user);const existing=db.prepare('SELECT enabled FROM user_mfa WHERE user_id=?').get(user.id);if(existing?.enabled)throw Object.assign(Error('Administrator MFA is already enabled'),{status:400});const secret=generateMfaSecret();db.prepare('INSERT INTO user_mfa(user_id,secret,enabled,confirmed_at) VALUES(?,?,0,NULL) ON CONFLICT(user_id) DO UPDATE SET secret=excluded.secret,enabled=0,confirmed_at=NULL').run(user.id,secret);const issuer=encodeURIComponent('Everwick');const label=encodeURIComponent(`Everwick:${user.email}`);return {secret,otpauth:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&digits=6&period=30`,enabled:false};}
export function confirmMfaSetup(db,user,code){requireAdmin(user);const row=db.prepare('SELECT secret,enabled FROM user_mfa WHERE user_id=?').get(user.id);if(!row?.secret)throw Object.assign(Error('Start MFA setup first'),{status:400});if(row.enabled)throw Object.assign(Error('Administrator MFA is already enabled'),{status:400});if(!verifyTotp(row.secret,code))throw Object.assign(Error('Invalid authenticator code'),{status:401});db.prepare('UPDATE user_mfa SET enabled=1,confirmed_at=? WHERE user_id=?').run(Date.now(),user.id);audit(db,user.id,'admin-mfa-enable',{});return {enabled:true};}
export function elevateAdmin(db,user,code){requireAdmin(user);const row=db.prepare('SELECT secret,enabled FROM user_mfa WHERE user_id=?').get(user.id);if(!row?.enabled)throw Object.assign(Error('Enable administrator MFA before requesting an elevated session'),{status:400});if(!verifyTotp(row.secret,code))throw Object.assign(Error('Invalid authenticator code'),{status:401});const token=randomId()+randomId();db.prepare('INSERT INTO admin_elevations(token,user_id,expires) VALUES(?,?,?)').run(tokenHash(token),user.id,Date.now()+15*60*1000);audit(db,user.id,'admin-mfa-elevate',{});return token;}
export function elevationCookie(token,clear=false){return `everwick_admin=${token||''}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${clear?0:900}${process.env.NODE_ENV==='production'?'; Secure':''}`;}
export function currentElevation(db,req,userId){const raw=req.headers.cookie?.match(/(?:^|;\s*)everwick_admin=([a-f0-9]+)/)?.[1];if(!raw)return false;const row=db.prepare('SELECT user_id FROM admin_elevations WHERE token=? AND expires>?').get(tokenHash(raw),Date.now());return !!row&&row.user_id===userId;}
/** Admin routes that mutate or expose privileged ops require elevation once MFA is enabled. */
export function requireAdminStepUp(db,user,req){requireAdmin(user);const mfa=mfaStatus(db,user.id);if(mfa.enabled&&!currentElevation(db,req,user.id))throw Object.assign(Error('Administrator MFA elevation required'),{status:401,code:'mfa_required'});return user;}

export function exportUserData(db,user){requireUser(user);const account=db.prepare('SELECT id,email,name,role,created_at FROM users WHERE id=?').get(user.id);const w=readWorld(db),p=w.players[user.id];const citizens=(p?.ownedCitizenIds||[]).map(id=>w.npcs.find(n=>n.id===id)).filter(Boolean).map(n=>({id:n.id,name:n.name,sex:n.sex||null,age:n.age,generation:n.generation||0,generationLabel:n.starter?'S':n.generationLabel,starter:!!n.starter,active:n.id===p.citizenId}));return {exported_at:Date.now(),account,purchases:db.prepare('SELECT id,tier,status,amount,refunded,mode,created_at FROM purchases WHERE user_id=? ORDER BY created_at').all(user.id),entitlements:db.prepare('SELECT purchase_id,tier,active,slots_total,slots_remaining,need_male,need_female FROM entitlements WHERE user_id=?').all(user.id),sessions:db.prepare('SELECT COUNT(*) n FROM sessions WHERE user_id=?').get(user.id).n,analytics:db.prepare('SELECT event,source,created_at,metadata FROM analytics WHERE user_id=? ORDER BY created_at DESC LIMIT 500').all(user.id),waitlist:db.prepare('SELECT email,consent,joined_at,source FROM waitlist WHERE email=?').all(account.email),audit:db.prepare('SELECT action,detail,created_at FROM audit WHERE user_id=? ORDER BY id DESC LIMIT 200').all(user.id),citizens};}

export function withdrawWaitlistConsent(db,{email,code}){const normalized=String(email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized))throw Error('Enter a valid email');const row=db.prepare('SELECT code,consent FROM waitlist WHERE email=?').get(normalized);if(!row)return {ok:true,withdrawn:false};if(code!=null&&String(code)&&row.code!==String(code))throw Object.assign(Error('Referral code did not match'),{status:403});db.prepare('UPDATE waitlist SET consent=0 WHERE email=?').run(normalized);return {ok:true,withdrawn:true};}

export function deleteUserAccount(db,user,{confirmEmail}){requireUser(user);if(String(confirmEmail||'').trim().toLowerCase()!==user.email)throw Object.assign(Error('Type your account email to confirm deletion'),{status:400});const tomb=`deleted-${user.id.slice(0,16)}@invalid.invalid`;
 return atomic(db,()=>{
  db.prepare('DELETE FROM sessions WHERE user_id=?').run(user.id);
  db.prepare('DELETE FROM admin_elevations WHERE user_id=?').run(user.id);
  db.prepare('DELETE FROM user_mfa WHERE user_id=?').run(user.id);
  db.prepare('DELETE FROM command_keys WHERE user_id=?').run(user.id);
  db.prepare('UPDATE entitlements SET active=0,slots_remaining=0,need_male=0,need_female=0 WHERE user_id=?').run(user.id);
  db.prepare('UPDATE waitlist SET consent=0 WHERE email=?').run(user.email);
  db.prepare("UPDATE users SET email=?,name='Deleted user',password=?,role='player' WHERE id=?").run(tomb,hashPassword(randomId()+randomId()),user.id);
  const w=readWorld(db);const p=w.players[user.id];if(p){p.accessRevoked=true;p.controlAt=0;p.name='Deleted user';p.accountName='Deleted user';if(p.citizenId){const n=w.npcs.find(n=>n.id===p.citizenId);if(n&&n.controllerId===user.id){n.controllerId=null;}}p.citizenId=null;p.ownedCitizenIds=[];}saveWorld(db,w);audit(db,user.id,'privacy-delete',{tomb});return {ok:true,deleted:true};
 });}
